version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: filament-payroll-app-dev
    ports:
      - "8282:80"
      - "2019:2019"  # Caddy admin API
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=pgsql-supabase
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/vendor
      - /app/node_modules
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - payroll-network-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  caddy_data:
  caddy_config:

networks:
  payroll-network-dev:
    driver: bridge